basePath: /
definitions:
  models.Purchase:
    properties:
      articleID:
        type: integer
      lieferant:
        type: string
      menge:
        type: integer
      preis:
        type: number
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: justin.kromlinger@stud.htwk-leipzig.de
    name: Justin Kromlinger
    url: https://hashworks.net
  description: Solution for 'Einkauf' backend task of https://sites.google.com/relaxdays.de/hackathon-relaxdays/startseite#h.klg8hathdmsn
  license:
    name: GNU Affero General Public License v3
    url: https://gnu.org/licenses/agpl.html
  title: Purchase Backend Task
  version: "1.0"
paths:
  /plot:
    get:
      parameters:
      - description: Article ID
        in: query
        name: x
        required: true
        type: string
      produces:
      - image/png
      responses:
        "200":
          description: ""
        "404":
          description: ""
      summary: Returns a plot of the price of an article over time
      tags:
      - Purchase
  /purchase:
    post:
      consumes:
      - application/json
      parameters:
      - description: Purchase to save
        in: body
        name: purchase
        required: true
        schema:
          $ref: '#/definitions/models.Purchase'
      responses:
        "204":
          description: ""
        "400":
          description: Invalid purchase
          schema:
            type: ""
      summary: Save a purchase
      tags:
      - Purchase
  /purchases:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Purchase'
            type: array
      summary: Returns all saved purchases
      tags:
      - Purchase
  /purchasesBetween:
    get:
      parameters:
      - description: Starting point in time in the format 13.03.2021 13:59:58
        in: query
        name: x
        required: true
        type: string
      - description: Ending point in time in the format 20.03.2021 15:59:58
        in: query
        name: "y"
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Purchase'
            type: array
        "400":
          description: Invalid points in time
          schema:
            type: ""
      summary: Returns all saved purchases between two points in time
      tags:
      - Purchase
  /purchasesForArticle:
    get:
      parameters:
      - description: ID of article to query
        in: query
        name: x
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Purchase'
            type: array
      summary: Returns all saved purchases for a given article
      tags:
      - Purchase
  /searchLieferant:
    get:
      parameters:
      - description: Vendor query
        in: query
        name: x
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Returns a list of vendors similar to a query
      tags:
      - Purchase
swagger: "2.0"
